repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        name: Format Python [black]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
      - id: markdownlint
        name: Lint Markdown
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pylint
        name: Lint Python [pylint]
        description: pylint pre-commit hook
        entry: pipenv run pylint
        language: python
        types: [python]
      - id: yamllint
        name: Lint YAML [yamllint]
        description: yamllint pre-commit hook
        entry: pipenv run yamllint
        language: python
        types: [yaml]
