name: Build
on:
  push:
    branches:
      - "master"
env:
  WORK_DIR: terraform-cloudfront
  SCRIPTS_DIR: ${{ env.WORK_DIR }}/scripts

jobs:
  version-bump:
    name: Version
    runs-on: ubuntu-latest
    environment: VERSION_BUMP
    steps:
      - name: Check-Out
        uses: actions/checkout@v3
        with:
          repository: jmgreg31/terraform-aws-cloudfront
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ env.WORK_DIR }}

      - name: Download Terraform
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd ${{ env.WORK_DIR }}
          wget https://releases.hashicorp.com/terraform/0.13.1/terraform_0.13.1_linux_amd64.zip
          unzip terraform_0.13.1_linux_amd64.zip
        shell: bash

      - name: Bump Version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python ${{ env.SCRIPTS_DIR }}/bump.py
        shell: bash

      # Use [norelease] or release:major | minor | patch to override
      - name: Release
        uses: rymndhng/release-on-push-action@v0.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          bump_version_scheme: patch
