name: Build
on:
  push:
    branches:
      - master
env:
  SCRIPTS_DIR: .github/scripts

jobs:
  version-bump:
    name: Version
    runs-on: ubuntu-latest
    environment: VERSION_BUMP
    steps:
      - name: Check-Out
        uses: actions/checkout@v3
        with:
          repository: jmgreg31/terraform-aws-cloudfront
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv sync --dev

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.13.1
          terraform_wrapper: false

      - name: Bump Version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pipenv run python ${{ env.SCRIPTS_DIR }}/bump.py
        shell: bash

      # Use [norelease] in PR Title
      # Add Label release:major | minor | patch to override
      - name: Release
        uses: rymndhng/release-on-push-action@v0.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          bump_version_scheme: patch
