name: Terraform - Staging
on:
  pull_request:
    branches:
      - "master"
env:
  WORK_DIR: terraform-cloudfront

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: TERRAFORM_STAGING
    steps:
      - name: Check-Out
        uses: actions/checkout@v3
        with:
          repository: jmgreg31/terraform-aws-cloudfront
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.WORK_DIR }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.13.1
          terraform_wrapper: false

      - name: Python Setup
        run: python -m pip install -r ${{ env.WORK_DIR }}/scripts/requirements.txt
        shell: bash

      - name: Staging Init
        id: staging
        run: pipenv run python ${{ env.WORK_DIR }}/scripts/staging.py
        shell: bash

      - name: Terraform Init
        id: init
        run: |
          cd ${{ env.WORK_DIR }}/example/
          terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: bash

      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ env.WORK_DIR }}/example/
          terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: bash
